### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by sunface** [KernelErr/awesome-rust-zh#11]
Rust语言圣经作为通用语言教材，虽然质量和知名度一般般，但是也应该放在前面，因为分门别类存放会不会更好一些？现在不知道为何放在了最后🤣，不过还是感谢你列了这本书～

**Comment by KernelErr** [comment]
感谢大佬指出，我晚些整理一下😃

**Comment by sunface** [comment]
谢谢～～ 还有个小建议，因为是中文书，所以书名可以考虑直接写 *Rust语言圣经*，省去之前的 *rust course* 英文部分哈～～

**Comment by sunface** [comment]
而且你这里的 Rust异步编程内容已经很老了。。给你推荐本新的( 高质量翻译，有兴趣可以试读下 )：https://github.com/studyrs/async-book

除此之外，还有 *Cargo Book* 和 *Too Many Lists* :
- https://github.com/studyrs/cargo-book
- https://github.com/studyrs/too-many-lists

既然是 awesome，那质量应该是第一位的，优于某些其它看不见的因素，你觉得呢 ：）

**Comment by sunface** [comment]
感谢采纳建议 ：）
